# The URL the site will be built for
base_url = "/"

title = "Dominik Nakamura"
description = "Dominik Nakamura's personal website"

generate_feed = true

taxonomies = [
    { name = "tags", feed = true },
    { name = "categories", feed = true },
]

compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "one-dark"

external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

smart_punctuation = true

[extra]
subtitle = "Backend Developer in Go, Rust and Kotlin"

menu = [
    { text = "About", link = "/about" },
    { text = "Projects", link = "/projects" },
]

social = [
    { name = "Github", url = "https://github.com/dnaka91" },
    { name = "Mastodon", url = "https://mastodon.technology/@dnaka91" },
    { name = "LinkedIn", url = "https://linkedin.com/in/dominik-nakamura" },
    { name = "Dev.to", url = "https://dev.to/dnaka91", icon = "dev" },
    { name = "Discord", url = "https://discord.gg/phxGsW8dWd" },
    { name = "Guilded", url = "https://www.guilded.gg/i/pB13lNPk" },
]
