name: Build
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ZOLA_VERSION: 0.19.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install packages
        run: bun install
      - name: Generate CSS
        run: bun run build
      - name: Install Zola
        run: docker pull ghcr.io/getzola/zola:v${ZOLA_VERSION}
      - name: Build website
        run: docker run -u "$(id -u):$(id -g)" -v $PWD:/app --workdir /app ghcr.io/getzola/zola:v${ZOLA_VERSION} build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
